workflows:
  ios-workflow:
    name: ATHLYTIX iOS
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd athlytix
          flutter pub get
      - name: Regenerate iOS folder
        script: |
          cd athlytix
          flutter create --platforms=ios .
      - name: Set Team ID
        script: |
          cd athlytix/ios
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = "U3XBJL6T8W";/g' Runner.xcodeproj/project.pbxproj
      - name: Install pods
        script: |
          cd athlytix/ios
          pod install --repo-update
      - name: Build iOS
        script: |
          cd athlytix
          flutter build ios --release --no-codesign
    artifacts:
      - athlytix/build/ios/iphoneos/*.app
