workflows:
  ios-workflow:
    name: BALLVYN iOS
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.athlytix.athlytix
    scripts:
      - name: Install dependencies
        script: |
          cd athlytix
          flutter pub get
      - name: Regenerate iOS folder
        script: |
          cd athlytix
          flutter create --platforms=ios .
      - name: Install pods
        script: |
          cd athlytix/ios
          pod install --repo-update
      - name: Add missing privacy manifests
        script: |
          PRIVACY_CONTENT='<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>NSPrivacyTracking</key>
            <false/>
            <key>NSPrivacyCollectedDataTypes</key>
            <array/>
            <key>NSPrivacyAccessedAPITypes</key>
            <array/>
          </dict>
          </plist>'

          for SDK in GTMSessionFetcher GoogleToolboxForMac; do
            find "$CM_BUILD_DIR/athlytix/ios" -name "${SDK}.framework" -type d | while read framework_path; do
              echo "Adding PrivacyInfo.xcprivacy to $framework_path"
              echo "$PRIVACY_CONTENT" > "$framework_path/PrivacyInfo.xcprivacy"
            done
          done
      - name: Initialize keychain
        script: keychain initialize
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up profiles
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          cd athlytix
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - athlytix/build/ios/ipa/*.ipa
      - athlytix/build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
