# ⚠️  NE PAS COMMITER CE FICHIER  —  ajouter à .gitignore
# Remplir avec vos vraies valeurs après avoir généré le keystore

storePassword=VOTRE_STORE_PASSWORD
keyPassword=VOTRE_KEY_PASSWORD
keyAlias=athlytix-key
storeFile=../athlytix-release-key.jks
